config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:index] do
    member do
      get :following, :followers
    end
  end
  resources :microposts do
    member do
      post "like", to: "favorites#create"
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :favorites, only: [:destroy]
  resources :relationships, only: [:create, :destroy]
  get "users/:id" => "users#show", as: :mypage
  root 'toppages#home'
  get '/help', to: 'toppages#help', as: 'helf'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :users, through: :favorites
  has_one_attached :image
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!

  def index
  end


  def show
    @micropost = Micropost.find(params[:id])
    @comment = @micropost.comments.build(user_id: current_user.id)
  end

  def new
    @micropost = current_user.microposts.build
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost.nil?
      @micropost.destroy
      flash[:success] = "削除に成功しました"
      redirect_to request.referrer || root_url
    else
      flash[:danger] = "削除に失敗しました"
      redirect_to root_url
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id%>">
  <%= link_to gravatar_for(micropost.user, size: 50) %>
  <span class="user"><%= micropost.user.username %></span>
    <span class="content"><%= micropost.content %></span>
    <% if micropost.image.attached? %>
      <span class="image"><%= image_tag micropost.image.variant(combine_options:{resize:"250x250^",crop:"250x250+0+0",gravity: :center}).processed %></span>
    <% end %>
    <span class="timestamp">
      <%= time_ago_in_words(micropost.created_at) %>
          前に投稿されました。
      <%= link_to '詳細', micropost_path(micropost) %>
      <%= link_to "お気に入りに登録", like_micropost_path(micropost), method: :post %>
      <%= link_to "お気に入り解除", favorite_path(micropost), method: :delete %>
      <% if current_user.id == micropost.user_id %>
        <%= link_to '削除する' , micropost, method: :delete, data: { confirm: "本当に削除しますか？"}  %>
      <% end %>
  </span>
</li>

app/views/microposts/index.html.erb
<h1>検索結果</h1>
<% if @search_microposts.any? %>
 <% @search_microposts.each do |micropost| %>
   <p><%= micropost.content %></p>
 <% end %>
 <% else %>
 <h1>検索結果はありません</h1>
<% end %>

app/views/microposts/new.html.erb
<%= render 'layouts/flash_messages' %>
<%= provide(:title, '写真投稿') %>
<h1>写真投稿</h1>
<%= form_for(@micropost) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "ここにコメントを入力してください" %>
  </div>
  <%= f.file_field :image %>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
<% end %>

app/views/microposts/show.html.erb
<%= render 'layouts/flash_messages' %>
<%= provide(:title, '写真個別') %>
<h1>写真個別ページ</h1>
<div class="microposts">
  <%= render @micropost %>
</div>
<% if @micropost.comments.any? %>
  <div class="comments">
    <h2>コメント</h2>
    <% @micropost.comments.each do |comment|  %>
      <li id="comment-<%= comment.id %>">
      <span class="content"><%= comment.content %></span>
      </span>
      </li>
    <% end %>
  </div>
<% end %>
<h2>コメントを追加</h2>
<%= render 'shared/comment_form' %>