config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:index] do
    member do
      get :following, :followers
    end
  end
  resources :microposts do
    member do
      post "like", to: "favorites#create"
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :favorites, only: [:destroy]
  resources :relationships, only: [:create, :destroy]
  get "users/:id" => "users#show", as: :mypage
  root 'toppages#home'
  get '/help', to: 'toppages#help', as: 'helf'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  validates :micropost_id, presence: true
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :users, through: :favorites
  has_one_attached :image
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id,
  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  has_many :microposts, dependent: :destroy
  has_many :comments,
  dependent: :destroy
  has_many :fav_microposts, through: :favorites, source: :micropost
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships,class_name: "Relationship", foreign_key: "followed_id",
  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end


  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.username = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def set_search
    @search = Micropost.ransack(params[:q])
    @search_microposts = @search.result.page(params[:page])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :introduce, :phone])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

  def create
    @micropost = Micropost.find(params[:micropost_id])
    @comment = @micropost.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "コメントに成功しました"
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "コメントの投稿に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @comment = @micropost.comments.find_by(id: params[:id])
    unless @comment.nil?
      @comment.destroy
      flash[:success] = "削除に成功しました"
      redirect_to request.referrer || root_url
    else
      flash[:danger] = "削除に失敗しました"
      redirect_to root_url
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @user_id = current_user.id
    @micropost_id = Micropost.find(params[:id]).id
    @favorite = Favorite.new(micropost_id: @micropost_id, user_id: @user_id)

    if @favorite.save
      redirect_to root_path
    end
  end

  def destroy
    @micropost_id = Micropost.find(params[:id]).id
    @favorite = Favorite.find_by(micropost_id: @micropost_id)
    if @favorite.destroy
      redirect_to root_path
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!

  def index
  end


  def show
    @micropost = Micropost.find(params[:id])
    @comment = @micropost.comments.build(user_id: current_user.id)
  end

  def new
    @micropost = current_user.microposts.build
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost.nil?
      @micropost.destroy
      flash[:success] = "削除に成功しました"
      redirect_to request.referrer || root_url
    else
      flash[:danger] = "削除に失敗しました"
      redirect_to root_url
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    respond_to do |format|
      format.html { redirect_to mypage_path(user) }
      format.js
    end
  end

  def destroy
     user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    respond_to do |format|
      format.html { redirect_to mypage_path(user) }
      format.js
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController

  def home
    if user_signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def uniq_title(title = "")
    normal_title = "Diver SNS"
    if title.empty?
      normal_title
    else
      title + " - " + normal_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      フォームの入力内容に <%= object.errors.count %>個のエラーがあります。
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<%= link_to '写真アップロード', new_micropost_path  %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Diver SNS", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to "Help", helf_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Mypage", mypage_path(current_user) %></li>
          <li><%= link_to "ユーザー編集", edit_user_registration_path %>
          <li><%= search_form_for @search, url: microposts_path do |f| %>
            <%= f.text_field :content_cont, placeholder: 'テキスト検索' %>
            <%= f.submit ("検索"), class: "search_btn "%>
            <% end %>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", helf_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= uniq_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for([@micropost, @comment]) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "コメントを入力してください" %>
  </div>
  <%= f.submit "コメントする", class: "btn btn-primary" %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
    <%# @feed_items = micropostの集合
    _micropostが呼び出される %>
  </ol>
<% end %>

app/views/shared/_stats.html.erb
<div class="stats">
  <strong id="following" class="stat">
    <%= user.following.count %>フォロー
  </strong>
  <strong id="followers" class="stat">
    <%= user.followers.count %> フォローワー
  </strong>
</div>